version: "3"
tasks:
  install-nomad-cli:
    desc: Install nomad cli via homebrew
    cmds:
      - brew tap hashicorp/tap
      - brew install hashicorp/tap/nomad
      - nomad -v

  start-dev-cluster:
    desc: Start a nomad dev cluster
    vars:
      DEFAULT_INTERFACE:
        sh: route -n get default | grep interface | awk '{print $2}'
    cmds:
      - export NOMAD_ADDR=http://localhost:4646
      - |
        nomad agent -dev \
          -bind 0.0.0.0 \
          -network-interface='{{.DEFAULT_INTERFACE}}'

  status:
    desc: Show nomad node status
    cmds:
      - nomad node status

  deploy-server-info:
    desc: Deploy a new version of server-info
    vars:
      TIMESTAMP:
        sh: date +%Y%m%d%H%M%S
    cmds:
      - cd apps/server-info && task build IMAGE_VERSION={{.TIMESTAMP}}
      - nomad job run -var IMAGE_VERSION={{.TIMESTAMP}} jobs/server-info.nomad

  deploy-dotnet-api:
    desc: Deploy a new version of dotnet-api
    vars:
      TIMESTAMP:
        sh: date +%Y%m%d%H%M%S
    cmds:
      - cd apps/dotnet-api && task build IMAGE_VERSION={{.TIMESTAMP}}
      - nomad job run -var IMAGE_VERSION={{.TIMESTAMP}} jobs/dotnet-api.nomad

  ssh-server:
    desc: Connect to a Nomad server via SSH
    vars:
      SERVER: "{{.SERVER | default 1}}"
      LB_IP: 51.137.124.4
    cmds:
      - |
        echo "Connecting to Nomad server {{.SERVER}} at {{.LB_IP}}..."
        ssh -i ~/.ssh/nomad_cluster -p 5000{{.SERVER}} azureuser@{{.LB_IP}}

  ssh-client:
    desc: Connect to a Nomad client via SSH
    vars:
      INSTANCE: "{{.INSTANCE | default 0}}"
    cmds:
      - ./scripts/ssh-to-nomad-client.sh --INSTANCE_ID {{.INSTANCE}}

  default:
    desc: List all available tasks
    cmds:
      - task --list-all
